title: Ankur Sharma

logo: "/IMG_20191211_151443-01.jpeg?raw=true"

decription: > Aspiring MERS stack developer.

<br><br>

<a href="mailto: uic17bca1427@gmail.com">uic17bca1427@gmail.com </a>
<br>
<a href= "https://www.linkedin.com/in/ankur-sharma-a34827172"> Linkdin </a>
<br>
<a href= "https://github.com/MeAnkur"> Github </a>

theme: jekyll-theme-minimal
